package com.datalake.datalake_subscriber_java.services.binding;

import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.datalake.datalake_subscriber_java.entities.DatalakeEntity;
import com.datalake.datalake_subscriber_java.services.mapper.PrePPDMapper;

@Component
public class PrePPDBinder {

    @Autowired
    private PrePPDMapper PrePPDMapper;

    public void updateEntityFromMessage(DatalakeEntity entity, Map<String, Object> messageData) {
        entity.setOrder_id(PrePPDMapper.getOrderId(messageData));
        entity.setCurrent_form_desc(PrePPDMapper.getCurrentFormDesc(messageData));
        entity.setAppl_no(PrePPDMapper.getApplNo(messageData));
        entity.setAppl_date(PrePPDMapper.getApplDate(messageData));
        entity.setOrder_date(PrePPDMapper.getOrderDate(messageData));
        entity.setAppl_contract_no(PrePPDMapper.getApplContractNo(messageData));
        entity.setMax_approval(PrePPDMapper.getMaxApproval(messageData));
        entity.setLast_approval(PrePPDMapper.getLastApproval(messageData));
        entity.setMax_deviasi(PrePPDMapper.getMaxDeviasi(messageData));
        // entity.setAppl_ppd_date(PrePPDMapper.getApplPpdDate(messageData));
        entity.setFin_type(PrePPDMapper.getFinType(messageData));
        entity.setFinance_product(PrePPDMapper.getFinanceProduct(messageData));
        entity.setCore_product(PrePPDMapper.getCoreProduct(messageData));
        entity.setArea(PrePPDMapper.getArea(messageData));
        entity.setBran_br_name(PrePPDMapper.getBranBrName(messageData));
        entity.setBran_br_id(PrePPDMapper.getBranBrId(messageData));
        entity.setOutlet_channel_desc(PrePPDMapper.getOutletChannelDesc(messageData));
        entity.setAppl_sales_through(PrePPDMapper.getApplSalesThrough(messageData));
        entity.setSales_throught(PrePPDMapper.getSalesThrought(messageData));
        // entity.setInitiall(PrePPDMapper.getInitiall(messageData));
        entity.setInternal_sales_force_code(PrePPDMapper.getInternalSalesForceCode(messageData));
        entity.setInternal_sales_force_nik(PrePPDMapper.getInternalSalesForceNik(messageData));
        entity.setInternal_sales_force_name(PrePPDMapper.getInternalSalesForceName(messageData));
        entity.setInternal_sales_force_job(PrePPDMapper.getInternalSalesForceJob(messageData));
        entity.setInterxt_sales_force1_name(PrePPDMapper.getInterxtSalesForce1Name(messageData));
        entity.setInterxt_sales_force1_npk(PrePPDMapper.getInterxtSalesForce1Npk(messageData));
        entity.setInterxt_sales_force1_job(PrePPDMapper.getInterxtSalesForce1Job(messageData));
        entity.setInterxt_sales_force2_name(PrePPDMapper.getInterxtSalesForce2Name(messageData));
        entity.setInterxt_sales_force2_npk(PrePPDMapper.getInterxtSalesForce2Npk(messageData));
        entity.setInterxt_sales_force2_job(PrePPDMapper.getInterxtSalesForce2Job(messageData));
        entity.setId_empl_mitra(PrePPDMapper.getIdEmplMitra(messageData));
        entity.setCompany(PrePPDMapper.getCompany(messageData));
        entity.setEmpl_nik_bank(PrePPDMapper.getEmplNikBank(messageData));
        entity.setNo_telephone(PrePPDMapper.getNoTelephone(messageData));
        entity.setBank_branch_id(PrePPDMapper.getBankBranchId(messageData));
        entity.setBank_office_location(PrePPDMapper.getBankOfficeLocation(messageData));
        entity.setKode_pekerjaan(PrePPDMapper.getKodePekerjaan(messageData));
        entity.setDebitur_no_npwp(PrePPDMapper.getDebiturNoNpwp(messageData));
        entity.setNpwp_type(PrePPDMapper.getNpwpType(messageData));
        entity.setBank_deal_empl(PrePPDMapper.getBankDealEmpl(messageData));
        entity.setEmpl_acc_no(PrePPDMapper.getEmplAccNo(messageData));
        entity.setEmpl_addr(PrePPDMapper.getEmplAddr(messageData));
        entity.setDlc(PrePPDMapper.getDlc(messageData));
        entity.setCred_deal_name(PrePPDMapper.getCredDealName(messageData));
        entity.setAppl_appl_tag1(PrePPDMapper.getApplApplTag1(messageData));
        entity.setAplication_tag1_desc(PrePPDMapper.getAplicationTag1Desc(messageData));
        entity.setAppl_appl_tag2(PrePPDMapper.getApplApplTag2(messageData));
        entity.setAplication_tax2_desc(PrePPDMapper.getAplicationTax2Desc(messageData));
        entity.setAppl_appl_tag3(PrePPDMapper.getApplApplTag3(messageData));
        entity.setAplication_tax3_desc(PrePPDMapper.getAplicationTax3Desc(messageData));
        entity.setStatus(PrePPDMapper.getStatus(messageData));
        entity.setAppl_objt_code(PrePPDMapper.getApplObjtCode(messageData));
        entity.setObjt_desc(PrePPDMapper.getObjtDesc(messageData));
        entity.setObbr_code(PrePPDMapper.getObbrCode(messageData));
        entity.setObbr_desc(PrePPDMapper.getObbrDesc(messageData));
        entity.setBahan_bakar(PrePPDMapper.getBahanBakar(messageData));
        entity.setObty_code(PrePPDMapper.getObtyCode(messageData));
        entity.setObty_desc(PrePPDMapper.getObtyDesc(messageData));
        entity.setObmo_code(PrePPDMapper.getObmoCode(messageData));
        entity.setObmo_desc(PrePPDMapper.getObmoDesc(messageData));
        entity.setObjt_obj_year(PrePPDMapper.getObjtObjYear(messageData));
        entity.setObjt_obj_mfg_year(PrePPDMapper.getObjtObjMfgYear(messageData));
        entity.setObjt_color(PrePPDMapper.getObjtColor(messageData));
        entity.setObjt_frame_no(PrePPDMapper.getObjtFrameNo(messageData));
        entity.setObjt_engine_no(PrePPDMapper.getObjtEngineNo(messageData));
        entity.setPurpose_desc(PrePPDMapper.getPurposeDesc(messageData));
        entity.setPaym_type_desc(PrePPDMapper.getPaymTypeDesc(messageData));
        entity.setBank_name(PrePPDMapper.getBankName(messageData));
        entity.setAppl_autodebit_acc_no(PrePPDMapper.getApplAutodebitAccNo(messageData));
        entity.setAppl_autodebit_acc_name(PrePPDMapper.getApplAutodebitAccName(messageData));
        entity.setAppl_mkpp_id(PrePPDMapper.getApplMkppId(messageData));
        entity.setMkpp_desc(PrePPDMapper.getMkppDesc(messageData));
        entity.setSubsidi_dp(PrePPDMapper.getSubsidiDp(messageData));
        entity.setJoint_promo(PrePPDMapper.getJointPromo(messageData));
        entity.setAdm_from_deal(PrePPDMapper.getAdmFromDeal(messageData));
        entity.setBbm_from_deal(PrePPDMapper.getBbmFromDeal(messageData));
        entity.setSubs_potong_pelunasan(PrePPDMapper.getSubsPotongPelunasan(messageData));
        entity.setSubsidi_klaim(PrePPDMapper.getSubsidiKlaim(messageData));
        entity.setDisc_kom(PrePPDMapper.getDiscKom(messageData));
        entity.setDiscount(PrePPDMapper.getDiscount(messageData));
        entity.setKomisi_langsung(PrePPDMapper.getKomisiLangsung(messageData));
        entity.setAdm_from_mu(PrePPDMapper.getAdmFromMu(messageData));
        entity.setBbm_from_mu(PrePPDMapper.getBbmFromMu(messageData));
        entity.setAppl_principal_amt(PrePPDMapper.getApplPrincipalAmt(messageData));
        entity.setPrin_plus_intr_amount(PrePPDMapper.getPrinPlusIntrAmount(messageData));
        entity.setAppl_top(PrePPDMapper.getApplTop(messageData));
        entity.setTot_adm_fee(PrePPDMapper.getTotAdmFee(messageData));
        entity.setAdm_fin(PrePPDMapper.getAdmFin(messageData));
        entity.setAdm_fee(PrePPDMapper.getAdmFee(messageData));
        entity.setOtr(PrePPDMapper.getOtr(messageData));
        entity.setAppl_adm_fee(PrePPDMapper.getApplAdmFee(messageData));
        entity.setAppl_gross_dp(PrePPDMapper.getApplGrossDp(messageData));
        entity.setAppl_net_dp(PrePPDMapper.getApplNetDp(messageData));
        entity.setDp_branch(PrePPDMapper.getDpBranch(messageData));
        entity.setAppl_int_flat_rate(PrePPDMapper.getApplIntFlatRate(messageData));
        entity.setAppl_int_eff_rate(PrePPDMapper.getApplIntEffRate(messageData));
        entity.setAppl_tot_ins_fee(PrePPDMapper.getApplTotInsFee(messageData));
        entity.setAppl_insr_financed(PrePPDMapper.getApplInsrFinanced(messageData));
        entity.setPaid_ins_fee(PrePPDMapper.getPaidInsFee(messageData));
        entity.setAppl_insr_buy_rate(PrePPDMapper.getApplInsrBuyRate(messageData));
        entity.setAppl_inst_amt(PrePPDMapper.getApplInstAmt(messageData));
        entity.setTot_ins_fee2(PrePPDMapper.getTotInsFee2(messageData));
        entity.setObjt_insr_financing_2(PrePPDMapper.getObjtInsrFinancing2(messageData));
        entity.setPaid_insr_fee2(PrePPDMapper.getPaidInsrFee2(messageData));
        entity.setTotal_provisi(PrePPDMapper.getTotalProvisi(messageData));
        entity.setProvisi_paid(PrePPDMapper.getProvisiPaid(messageData));
        entity.setProvisi_fin(PrePPDMapper.getProvisiFin(messageData));
        entity.setInstalment_amount(PrePPDMapper.getInstalmentAmount(messageData));
        entity.setCust_type(PrePPDMapper.getCustType(messageData));
        entity.setCust_no(PrePPDMapper.getCustNo(messageData));
        entity.setCust_sid_name(PrePPDMapper.getCustSidName(messageData));
        entity.setSex(PrePPDMapper.getSex(messageData));
        entity.setPhone_no(PrePPDMapper.getPhoneNo(messageData));
        entity.setDebitur_no_hp_1(PrePPDMapper.getDebiturNoHp1(messageData));
        entity.setCust_id_no(PrePPDMapper.getCustIdNo(messageData));
        entity.setMother_name(PrePPDMapper.getMotherName(messageData));
        entity.setCust_birth_date(PrePPDMapper.getCustBirthDate(messageData));
        entity.setCust_birth_place(PrePPDMapper.getCustBirthPlace(messageData));
        entity.setCust_monthly_income(PrePPDMapper.getCustMonthlyIncome(messageData));
        entity.setCust_address(PrePPDMapper.getCustAddress(messageData));
        entity.setRt(PrePPDMapper.getRt(messageData));
        entity.setRw(PrePPDMapper.getRw(messageData));
        entity.setCust_zip_code(PrePPDMapper.getCustZipCode(messageData));
        entity.setCust_kelurahan(PrePPDMapper.getCustKelurahan(messageData));
        entity.setCust_kecamatan(PrePPDMapper.getCustKecamatan(messageData));
        entity.setCust_kab_kota(PrePPDMapper.getCustKabKota(messageData));
        entity.setCust_provinsi(PrePPDMapper.getCustProvinsi(messageData));
        entity.setComp_name(PrePPDMapper.getCompName(messageData));
        entity.setComp_type(PrePPDMapper.getCompType(messageData));
        entity.setEconomic_sec1(PrePPDMapper.getEconomicSec1(messageData));
        entity.setEconomic_sec2(PrePPDMapper.getEconomicSec2(messageData));
        entity.setEconomic_sec3(PrePPDMapper.getEconomicSec3(messageData));
        entity.setNature_buss(PrePPDMapper.getNatureBuss(messageData));
        entity.setCust_curr_year_of_work(PrePPDMapper.getCustCurrYearOfWork(messageData));
        entity.setCom_status_tempat(PrePPDMapper.getComStatusTempat(messageData));
        entity.setCom_lokasi_usaha(PrePPDMapper.getComLokasiUsaha(messageData));
        entity.setCom_total_employee(PrePPDMapper.getComTotalEmployee(messageData));
        entity.setCom_no_of_year_buss(PrePPDMapper.getComNoOfYearBuss(messageData));
        entity.setCust_pro_lama_profesi(PrePPDMapper.getCustProLamaProfesi(messageData));
        entity.setJenis_profesi(PrePPDMapper.getJenisProfesi(messageData));
        // entity.setApproved_date(PrePPDMapper.getApprovedDate(messageData));
        entity.setStatus_appr(PrePPDMapper.getStatusAppr(messageData));
        // entity.setTanggal_cetak_po(PrePPDMapper.getTanggalCetakPo(messageData));
        entity.setApprove_note(PrePPDMapper.getApproveNote(messageData));
        // entity.setTanggal_fpd(PrePPDMapper.getTanggalFpd(messageData));
        entity.setNo_fpd(PrePPDMapper.getNoFpd(messageData));
        entity.setNpk_cmh(PrePPDMapper.getNpkCmh(messageData));
        entity.setNama_cmh(PrePPDMapper.getNamaCmh(messageData));
        entity.setInstallment_type(PrePPDMapper.getInstallmentType(messageData));
        entity.setAdvance_arrear(PrePPDMapper.getAdvanceArrear(messageData));
        entity.setTahun_kendaraan(PrePPDMapper.getTahunKendaraan(messageData));
        entity.setInsurance_fee(PrePPDMapper.getInsuranceFee(messageData));
        entity.setAppl_admf_komisi_amt(PrePPDMapper.getApplAdmfKomisiAmt(messageData));
        // entity.setStatus_cancel(PrePPDMapper.getStatusCancel(messageData));
        // entity.setCancel_pocl(PrePPDMapper.getCancelPocl(messageData));
        // entity.setMufnet(PrePPDMapper.getMufnet(messageData));
        entity.setPenggolongan_product(PrePPDMapper.getPenggolonganProduct(messageData));
        entity.setBank_wilayah_mdr(PrePPDMapper.getBankWilayahMdr(messageData));
        entity.setBank_area_mdr(PrePPDMapper.getBankAreaMdr(messageData));
        entity.setFlag_cancel(PrePPDMapper.getFlagCancel(messageData));
        // entity.setCancel_ppd_date(PrePPDMapper.getCancelPpdDate(messageData));
        entity.setStatus_repo(PrePPDMapper.getStatusRepo(messageData));
        entity.setNik_mca(PrePPDMapper.getNikMca(messageData));
        entity.setNama_mca(PrePPDMapper.getNamaMca(messageData));
        entity.setFirst_name(PrePPDMapper.getFirstName(messageData));
        entity.setLast_name(PrePPDMapper.getLastName(messageData));
        entity.setInsurance_type_code(PrePPDMapper.getInsuranceTypeCode(messageData));
        entity.setInsurance_type(PrePPDMapper.getInsuranceType(messageData));
        entity.setNama_bpkb(PrePPDMapper.getNamaBpkb(messageData));
        entity.setOccupation(PrePPDMapper.getOccupation(messageData));
        entity.setStatus_indent(PrePPDMapper.getStatusIndent(messageData));
        // entity.setCancel_reject_date_ca(PrePPDMapper.getCancelRejectDateCa(messageData));
        // entity.setCancel_reject_date_mkt(PrePPDMapper.getCancelRejectDateMkt(messageData));
        entity.setLtv(PrePPDMapper.getLtv(messageData));
        entity.setMarital(PrePPDMapper.getMarital(messageData));
        entity.setEducation(PrePPDMapper.getEducation(messageData));
        entity.setStatus_jf_bmri(PrePPDMapper.getStatusJfBmri(messageData));
        entity.setPrin_jf_bmri(PrePPDMapper.getPrinJfBmri(messageData));
        entity.setIntr_jf_bmri(PrePPDMapper.getIntrJfBmri(messageData));
        entity.setMkt_prod(PrePPDMapper.getMktProd(messageData));
        entity.setSumber_nasabah(PrePPDMapper.getSumberNasabah(messageData));
        entity.setProgramm(PrePPDMapper.getProgramm(messageData));
        entity.setEducation_code(PrePPDMapper.getEducationCode(messageData));
        entity.setOccupation_code(PrePPDMapper.getOccupationCode(messageData));
        entity.setEconomic_sector_code1(PrePPDMapper.getEconomicSectorCode1(messageData));
        entity.setEconomic_sector_code2(PrePPDMapper.getEconomicSectorCode2(messageData));
        entity.setEconomic_sector_code3(PrePPDMapper.getEconomicSectorCode3(messageData));
        entity.setRo_ao(PrePPDMapper.getRoAo(messageData));
        entity.setDsr(PrePPDMapper.getDsr(messageData));
        entity.setVehicle_type(PrePPDMapper.getVehicleType(messageData));
        entity.setDependent(PrePPDMapper.getDependent(messageData));
        entity.setLama_tinggal(PrePPDMapper.getLamaTinggal(messageData));
        entity.setBal_prin(PrePPDMapper.getBalPrin(messageData));
        entity.setOvd(PrePPDMapper.getOvd(messageData));
        entity.setFirst_installment_method(PrePPDMapper.getFirstInstallmentMethod(messageData));
        entity.setStatus_aging(PrePPDMapper.getStatusAging(messageData));
        entity.setSumber_data_desc(PrePPDMapper.getSumberDataDesc(messageData));
        entity.setSumber_order_desc(PrePPDMapper.getSumberOrderDesc(messageData));
        entity.setPortfolio_code(PrePPDMapper.getPortfolioCode(messageData));
        entity.setPortfolio_desc(PrePPDMapper.getPortfolioDesc(messageData));
        entity.setMogr_code(PrePPDMapper.getMogrCode(messageData));
        entity.setMogr_desc(PrePPDMapper.getMogrDesc(messageData));
        entity.setObmo_genre(PrePPDMapper.getObmoGenre(messageData));
        entity.setNpk_cmh_2(PrePPDMapper.getNpkCmh2(messageData));
        entity.setNama_cmh_2(PrePPDMapper.getNamaCmh2(messageData));
        entity.setTipe_restructuring(PrePPDMapper.getTipeRestructuring(messageData));
        entity.setNo_contract_old(PrePPDMapper.getNoContractOld(messageData));
        // entity.setScreening_1_date(PrePPDMapper.getScreening1Date(messageData));
        // entity.setScreening_2_date(PrePPDMapper.getScreening2Date(messageData));
        // entity.setInsert_date_reguler_survey(PrePPDMapper.getInsertDateRegulerSurvey(messageData));
        // entity.setScreening_3_date(PrePPDMapper.getScreening3Date(messageData));
        // entity.setNik_1(PrePPDMapper.getNik1(messageData));
        // entity.setNama_1(PrePPDMapper.getNama1(messageData));
        // entity.setJobcode_1(PrePPDMapper.getJobcode1(messageData));
        // entity.setResult_1(PrePPDMapper.getResult1(messageData));
        // entity.setDate_1(PrePPDMapper.getDate1(messageData));
        // entity.setNik_2(PrePPDMapper.getNik2(messageData));
        // entity.setNama_2(PrePPDMapper.getNama2(messageData));
        // entity.setJobcode_2(PrePPDMapper.getJobcode2(messageData));
        // entity.setResult_2(PrePPDMapper.getResult2(messageData));
        // entity.setDate_2(PrePPDMapper.getDate2(messageData));
        // entity.setNik_3(PrePPDMapper.getNik3(messageData));
        // entity.setNama_3(PrePPDMapper.getNama3(messageData));
        // entity.setJobcode_3(PrePPDMapper.getJobcode3(messageData));
        // entity.setResult_3(PrePPDMapper.getResult3(messageData));
        // entity.setDate_3(PrePPDMapper.getDate3(messageData));
        // entity.setNik_4(PrePPDMapper.getNik4(messageData));
        // entity.setNama_4(PrePPDMapper.getNama4(messageData));
        // entity.setJobcode_4(PrePPDMapper.getJobcode4(messageData));
        // entity.setResult_4(PrePPDMapper.getResult4(messageData));
        // entity.setDate_4(PrePPDMapper.getDate4(messageData));
        // entity.setNik_5(PrePPDMapper.getNik5(messageData));
        // entity.setNama_5(PrePPDMapper.getNama5(messageData));
        // entity.setJobcode_5(PrePPDMapper.getJobcode5(messageData));
        // entity.setResult_5(PrePPDMapper.getResult5(messageData));
        // entity.setDate_5(PrePPDMapper.getDate5(messageData));
        // entity.setNik_6(PrePPDMapper.getNik6(messageData));
        // entity.setNama_6(PrePPDMapper.getNama6(messageData));
        // entity.setJobcode_6(PrePPDMapper.getJobcode6(messageData));
        // entity.setResult_6(PrePPDMapper.getResult6(messageData));
        // entity.setDate_6(PrePPDMapper.getDate6(messageData));
        // entity.setNik_7(PrePPDMapper.getNik7(messageData));
        // entity.setNama_7(PrePPDMapper.getNama7(messageData));
        // entity.setJobcode_7(PrePPDMapper.getJobcode7(messageData));
        // entity.setResult_7(PrePPDMapper.getResult7(messageData));
        // entity.setDate_7(PrePPDMapper.getDate7(messageData));
        // entity.setNik_8(PrePPDMapper.getNik8(messageData));
        // entity.setNama_8(PrePPDMapper.getNama8(messageData));
        // entity.setJobcode_8(PrePPDMapper.getJobcode8(messageData));
        // entity.setResult_8(PrePPDMapper.getResult8(messageData));
        // entity.setDate_8(PrePPDMapper.getDate8(messageData));
        // entity.setNik_9(PrePPDMapper.getNik9(messageData));
        // entity.setNama_9(PrePPDMapper.getNama9(messageData));
        // entity.setJobcode_9(PrePPDMapper.getJobcode9(messageData));
        // entity.setResult_9(PrePPDMapper.getResult9(messageData));
        // entity.setDate_9(PrePPDMapper.getDate9(messageData));
        // entity.setNik_10(PrePPDMapper.getNik10(messageData));
        // entity.setNama_10(PrePPDMapper.getNama10(messageData));
        // entity.setJobcode_10(PrePPDMapper.getJobcode10(messageData));
        // entity.setResult_10(PrePPDMapper.getResult10(messageData));
        // entity.setDate_10(PrePPDMapper.getDate10(messageData));
        // entity.setNik_11(PrePPDMapper.getNik11(messageData));
        // entity.setNama_11(PrePPDMapper.getNama11(messageData));
        // entity.setJobcode_11(PrePPDMapper.getJobcode11(messageData));
        // entity.setResult_11(PrePPDMapper.getResult11(messageData));
        // entity.setDate_11(PrePPDMapper.getDate11(messageData));
        // entity.setNik_12(PrePPDMapper.getNik12(messageData));
        // entity.setNama_12(PrePPDMapper.getNama12(messageData));
        // entity.setJobcode_12(PrePPDMapper.getJobcode12(messageData));
        // entity.setResult_12(PrePPDMapper.getResult12(messageData));
        // entity.setDate_12(PrePPDMapper.getDate12(messageData));
        // entity.setNik_13(PrePPDMapper.getNik13(messageData));
        // entity.setNama_13(PrePPDMapper.getNama13(messageData));
        // entity.setJobcode_13(PrePPDMapper.getJobcode13(messageData));
        // entity.setResult_13(PrePPDMapper.getResult13(messageData));
        // entity.setDate_13(PrePPDMapper.getDate13(messageData));
        // entity.setNik_14(PrePPDMapper.getNik14(messageData));
        // entity.setNama_14(PrePPDMapper.getNama14(messageData));
        // entity.setJobcode_14(PrePPDMapper.getJobcode14(messageData));
        // entity.setResult_14(PrePPDMapper.getResult14(messageData));
        // entity.setDate_14(PrePPDMapper.getDate14(messageData));
        // entity.setNik_15(PrePPDMapper.getNik15(messageData));
        // entity.setNama_15(PrePPDMapper.getNama15(messageData));
        // entity.setJobcode_15(PrePPDMapper.getJobcode15(messageData));
        // entity.setResult_15(PrePPDMapper.getResult15(messageData));
        // entity.setDate_15(PrePPDMapper.getDate15(messageData));
        // entity.setDate_cancel_reguler(PrePPDMapper.getDateCancelReguler(messageData));
        // entity.setDate_cancel_pocl(PrePPDMapper.getDateCancelPocl(messageData));
        // entity.setInsert_date_pocl(PrePPDMapper.getInsertDatePocl(messageData));
        // entity.setPrint_date_pocl(PrePPDMapper.getPrintDatePocl(messageData));
        // entity.setDate_full_data_entry(PrePPDMapper.getDateFullDataEntry(messageData));
        entity.setCancel_todolist(PrePPDMapper.getCancelTodolist(messageData));
        // entity.setDate_cancel_kyc(PrePPDMapper.getDateCancelKyc(messageData));
        entity.setFin_prod_desc(PrePPDMapper.getFinProdDesc(messageData));
        entity.setFin_purpose_desc(PrePPDMapper.getFinPurposeDesc(messageData));
        entity.setNature_of_financing(PrePPDMapper.getNatureOfFinancing(messageData));
        entity.setInitial_1(PrePPDMapper.getInitial1(messageData));
        entity.setOutlet(PrePPDMapper.getOutlet(messageData));
        entity.setInternal_sales_force2_code(PrePPDMapper.getInternalSalesForce2Code(messageData));
        entity.setInternal_sales_force2_nik(PrePPDMapper.getInternalSalesForce2Nik(messageData));
        entity.setInternal_sales_force2_name(PrePPDMapper.getInternalSalesForce2Name(messageData));
        entity.setInternal_sales_force2_job(PrePPDMapper.getInternalSalesForce2Job(messageData));
        entity.setInitial_2(PrePPDMapper.getInitial2(messageData));
        entity.setPengajuan_telesurvey(PrePPDMapper.getPengajuanTelesurvey(messageData));
        entity.setProses_pembiayaan_telesurvey(PrePPDMapper.getProsesPembiayaanTelesurvey(messageData));
        entity.setDate_telesurvey(PrePPDMapper.getDateTelesurvey(messageData));
        // entity.setInsert_by_telesurvey(PrePPDMapper.getInsertByTelesurvey(messageData));
        entity.setStatus_kyc(PrePPDMapper.getStatusKyc(messageData));
        // entity.setDate_kyc(PrePPDMapper.getDateKyc(messageData));
        // entity.setInsert_by_kyc(PrePPDMapper.getInsertByKyc(messageData));
        entity.setHasil_kyc(PrePPDMapper.getHasilKyc(messageData));
        entity.setArea_id(PrePPDMapper.getAreaId(messageData));
        // entity.setInsert_date(PrePPDMapper.getInsertDate(messageData));
        // entity.setUpdate_date(PrePPDMapper.getUpdateDate(messageData));
        entity.setAsuransi_kendaraan(PrePPDMapper.getAsuransiKendaraan(messageData));
        entity.setAsuransi_tambahan(PrePPDMapper.getAsuransiTambahan(messageData));
        entity.setEng_capacity(PrePPDMapper.getEngCapacity(messageData));
        entity.setSkema_pembiayaan(PrePPDMapper.getSkemaPembiayaan(messageData));
        entity.setTotal_interest_amount(PrePPDMapper.getTotalInterestAmount(messageData));
        entity.setInsurance_credit_fee(PrePPDMapper.getInsuranceCreditFee(messageData));
        entity.setJatuh_tempo(PrePPDMapper.getJatuhTempo(messageData));
        entity.setObj_pembiayaan(PrePPDMapper.getObjPembiayaan(messageData));
        entity.setInternal_sales_head(PrePPDMapper.getInternalSalesHead(messageData));
        entity.setFin_scheme_code(PrePPDMapper.getFinSchemeCode(messageData));
        entity.setNo_obligor_id(PrePPDMapper.getNoObligorId(messageData));
        entity.setNo_po_cl(PrePPDMapper.getNoPoCl(messageData));
        entity.setInterest_amount(PrePPDMapper.getInterestAmount(messageData));
        entity.setBiaya_asuransi_tambahan(PrePPDMapper.getBiayaAsuransiTambahan(messageData));
        // entity.setJob_internal_sales_forced(PrePPDMapper.getJobInternalSalesForced(messageData));
        // entity.setNama_internal_sales_forced(PrePPDMapper.getNamaInternalSalesForced(messageData));
        entity.setKeterangan_po(PrePPDMapper.getKeteranganPo(messageData));
        entity.setNilai_pelunasan(PrePPDMapper.getNilaiPelunasan(messageData));
        entity.setAlasan_cancel_po_cl(PrePPDMapper.getAlasanCancelPoCl(messageData));
        entity.setNotes_cancel_po_cl(PrePPDMapper.getNotesCancelPoCl(messageData));
        entity.setNik_reject_cancel_marketing(PrePPDMapper.getNikRejectCancelMarketing(messageData));
        entity.setUser_reject_cancel_marketing(PrePPDMapper.getUserRejectCancelMarketing(messageData));
        entity.setPic_dealer(PrePPDMapper.getPicDealer(messageData));
        entity.setFlagging_reject_cancel_mkt(PrePPDMapper.getFlaggingRejectCancelMkt(messageData));
        entity.setDeskripsi_reject_cancel_mkt(PrePPDMapper.getDeskripsiRejectCancelMkt(messageData));
        entity.setAlasan_reject_cancel_mkt(PrePPDMapper.getAlasanRejectCancelMkt(messageData));
        entity.setReject_cancel_source_app(PrePPDMapper.getRejectCancelSourceApp(messageData));
        // entity.setDeskripsi_source_aplikasi(PrePPDMapper.getDeskripsiSourceAplikasi(messageData));
        entity.setAlasan_koreksi_po(PrePPDMapper.getAlasanKoreksiPo(messageData));
        entity.setNik_koreksi_po(PrePPDMapper.getNikKoreksiPo(messageData));
        // entity.setTanggal_koreksi_po(PrePPDMapper.getTanggalKoreksiPo(messageData));
        entity.setTotal_koreksi_po(PrePPDMapper.getTotalKoreksiPo(messageData));
        // entity.setCara_bayar_angsuran(PrePPDMapper.getCaraBayarAngsuran(messageData));
        entity.setStatus_aplikasi(PrePPDMapper.getStatusAplikasi(messageData));
        entity.setJumlah_nasabah_ditolak(PrePPDMapper.getJumlahNasabahDitolak(messageData));
        entity.setJumlah_cetak_po_cl(PrePPDMapper.getJumlahCetakPoCl(messageData));
        entity.setJumlah_po_cl_belum_cetak(PrePPDMapper.getJumlahPoClBelumCetak(messageData));
        entity.setJumlah_cancel_po_cl(PrePPDMapper.getJumlahCancelPoCl(messageData));
        entity.setJumlah_koreksi_po_cl(PrePPDMapper.getJumlahKoreksiPoCl(messageData));
        entity.setJumlah_po_cl_pending(PrePPDMapper.getJumlahPoClPending(messageData));
        entity.setJumlah_nasabah_cancel_ppd(PrePPDMapper.getJumlahNasabahCancelPpd(messageData));
        entity.setJumlah_tagihan_belum_ppd(PrePPDMapper.getJumlahTagihanBelumPpd(messageData));
        entity.setJumlah_reject_cancel_marketing(PrePPDMapper.getJumlahRejectCancelMarketing(messageData));
        // entity.setTipe_debitur(PrePPDMapper.getTipeDebitur(messageData));
        // entity.setTanggal_entry(PrePPDMapper.getTanggalEntry(messageData));
        // entity.setTanggal_approval(PrePPDMapper.getTanggalApproval(messageData));
        // entity.setTanggal_cetak(PrePPDMapper.getTanggalCetak(messageData));
        // entity.setTanggal_cancel(PrePPDMapper.getTanggalCancel(messageData));
        // entity.setTanggal_koreksi(PrePPDMapper.getTanggalKoreksi(messageData));
    }

}
