package com.datalake.datalake_subscriber_java.services.binding;

import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.datalake.datalake_subscriber_java.entities.DatalakeEntity;
import com.datalake.datalake_subscriber_java.services.mapper.VerdatMapper;

@Component
public class VerdatBinder {

    @Autowired
    private VerdatMapper verdatMapper;

    public void updateEntityFromMessage(DatalakeEntity entity, Map<String, Object> messageData) {
        entity.setOrder_id(verdatMapper.getOrderId(messageData));
        entity.setCurrent_form_desc(verdatMapper.getCurrentFormDesc(messageData));
        entity.setAppl_no(verdatMapper.getApplNo(messageData));
        entity.setAppl_date(verdatMapper.getApplDate(messageData));
        entity.setOrder_date(verdatMapper.getOrderDate(messageData));
        entity.setAppl_contract_no(verdatMapper.getApplContractNo(messageData));
        entity.setMax_approval(verdatMapper.getMaxApproval(messageData));
        entity.setLast_approval(verdatMapper.getLastApproval(messageData));
        entity.setMax_deviasi(verdatMapper.getMaxDeviasi(messageData));
        // entity.setAppl_ppd_date(verdatMapper.getApplPpdDate(messageData));
        entity.setFin_type(verdatMapper.getFinType(messageData));
        entity.setFinance_product(verdatMapper.getFinanceProduct(messageData));
        entity.setCore_product(verdatMapper.getCoreProduct(messageData));
        entity.setArea(verdatMapper.getArea(messageData));
        entity.setBran_br_name(verdatMapper.getBranBrName(messageData));
        entity.setBran_br_id(verdatMapper.getBranBrId(messageData));
        entity.setOutlet_channel_desc(verdatMapper.getOutletChannelDesc(messageData));
        entity.setAppl_sales_through(verdatMapper.getApplSalesThrough(messageData));
        entity.setSales_throught(verdatMapper.getSalesThrought(messageData));
        // entity.setInitiall(verdatMapper.getInitiall(messageData));
        entity.setInternal_sales_force_code(verdatMapper.getInternalSalesForceCode(messageData));
        entity.setInternal_sales_force_nik(verdatMapper.getInternalSalesForceNik(messageData));
        entity.setInternal_sales_force_name(verdatMapper.getInternalSalesForceName(messageData));
        entity.setInternal_sales_force_job(verdatMapper.getInternalSalesForceJob(messageData));
        entity.setInterxt_sales_force1_name(verdatMapper.getInterxtSalesForce1Name(messageData));
        entity.setInterxt_sales_force1_npk(verdatMapper.getInterxtSalesForce1Npk(messageData));
        entity.setInterxt_sales_force1_job(verdatMapper.getInterxtSalesForce1Job(messageData));
        entity.setInterxt_sales_force2_name(verdatMapper.getInterxtSalesForce2Name(messageData));
        entity.setInterxt_sales_force2_npk(verdatMapper.getInterxtSalesForce2Npk(messageData));
        entity.setInterxt_sales_force2_job(verdatMapper.getInterxtSalesForce2Job(messageData));
        entity.setId_empl_mitra(verdatMapper.getIdEmplMitra(messageData));
        entity.setCompany(verdatMapper.getCompany(messageData));
        entity.setEmpl_nik_bank(verdatMapper.getEmplNikBank(messageData));
        entity.setNo_telephone(verdatMapper.getNoTelephone(messageData));
        entity.setBank_branch_id(verdatMapper.getBankBranchId(messageData));
        entity.setBank_office_location(verdatMapper.getBankOfficeLocation(messageData));
        entity.setKode_pekerjaan(verdatMapper.getKodePekerjaan(messageData));
        entity.setDebitur_no_npwp(verdatMapper.getDebiturNoNpwp(messageData));
        entity.setNpwp_type(verdatMapper.getNpwpType(messageData));
        entity.setBank_deal_empl(verdatMapper.getBankDealEmpl(messageData));
        entity.setEmpl_acc_no(verdatMapper.getEmplAccNo(messageData));
        entity.setEmpl_addr(verdatMapper.getEmplAddr(messageData));
        entity.setDlc(verdatMapper.getDlc(messageData));
        entity.setCred_deal_name(verdatMapper.getCredDealName(messageData));
        entity.setAppl_appl_tag1(verdatMapper.getApplApplTag1(messageData));
        entity.setAplication_tag1_desc(verdatMapper.getAplicationTag1Desc(messageData));
        entity.setAppl_appl_tag2(verdatMapper.getApplApplTag2(messageData));
        entity.setAplication_tax2_desc(verdatMapper.getAplicationTax2Desc(messageData));
        entity.setAppl_appl_tag3(verdatMapper.getApplApplTag3(messageData));
        entity.setAplication_tax3_desc(verdatMapper.getAplicationTax3Desc(messageData));
        entity.setStatus(verdatMapper.getStatus(messageData));
        entity.setAppl_objt_code(verdatMapper.getApplObjtCode(messageData));
        entity.setObjt_desc(verdatMapper.getObjtDesc(messageData));
        entity.setObbr_code(verdatMapper.getObbrCode(messageData));
        entity.setObbr_desc(verdatMapper.getObbrDesc(messageData));
        entity.setBahan_bakar(verdatMapper.getBahanBakar(messageData));
        entity.setObty_code(verdatMapper.getObtyCode(messageData));
        entity.setObty_desc(verdatMapper.getObtyDesc(messageData));
        entity.setObmo_code(verdatMapper.getObmoCode(messageData));
        entity.setObmo_desc(verdatMapper.getObmoDesc(messageData));
        entity.setObjt_obj_year(verdatMapper.getObjtObjYear(messageData));
        entity.setObjt_obj_mfg_year(verdatMapper.getObjtObjMfgYear(messageData));
        entity.setObjt_color(verdatMapper.getObjtColor(messageData));
        entity.setObjt_frame_no(verdatMapper.getObjtFrameNo(messageData));
        entity.setObjt_engine_no(verdatMapper.getObjtEngineNo(messageData));
        entity.setPurpose_desc(verdatMapper.getPurposeDesc(messageData));
        entity.setPaym_type_desc(verdatMapper.getPaymTypeDesc(messageData));
        entity.setBank_name(verdatMapper.getBankName(messageData));
        entity.setAppl_autodebit_acc_no(verdatMapper.getApplAutodebitAccNo(messageData));
        entity.setAppl_autodebit_acc_name(verdatMapper.getApplAutodebitAccName(messageData));
        entity.setAppl_mkpp_id(verdatMapper.getApplMkppId(messageData));
        entity.setMkpp_desc(verdatMapper.getMkppDesc(messageData));
        entity.setSubsidi_dp(verdatMapper.getSubsidiDp(messageData));
        entity.setJoint_promo(verdatMapper.getJointPromo(messageData));
        entity.setAdm_from_deal(verdatMapper.getAdmFromDeal(messageData));
        entity.setBbm_from_deal(verdatMapper.getBbmFromDeal(messageData));
        entity.setSubs_potong_pelunasan(verdatMapper.getSubsPotongPelunasan(messageData));
        entity.setSubsidi_klaim(verdatMapper.getSubsidiKlaim(messageData));
        entity.setDisc_kom(verdatMapper.getDiscKom(messageData));
        entity.setDiscount(verdatMapper.getDiscount(messageData));
        entity.setKomisi_langsung(verdatMapper.getKomisiLangsung(messageData));
        entity.setAdm_from_mu(verdatMapper.getAdmFromMu(messageData));
        entity.setBbm_from_mu(verdatMapper.getBbmFromMu(messageData));
        entity.setAppl_principal_amt(verdatMapper.getApplPrincipalAmt(messageData));
        entity.setPrin_plus_intr_amount(verdatMapper.getPrinPlusIntrAmount(messageData));
        entity.setAppl_top(verdatMapper.getApplTop(messageData));
        entity.setTot_adm_fee(verdatMapper.getTotAdmFee(messageData));
        entity.setAdm_fin(verdatMapper.getAdmFin(messageData));
        entity.setAdm_fee(verdatMapper.getAdmFee(messageData));
        entity.setOtr(verdatMapper.getOtr(messageData));
        entity.setAppl_adm_fee(verdatMapper.getApplAdmFee(messageData));
        entity.setAppl_gross_dp(verdatMapper.getApplGrossDp(messageData));
        entity.setAppl_net_dp(verdatMapper.getApplNetDp(messageData));
        entity.setDp_branch(verdatMapper.getDpBranch(messageData));
        entity.setAppl_int_flat_rate(verdatMapper.getApplIntFlatRate(messageData));
        entity.setAppl_int_eff_rate(verdatMapper.getApplIntEffRate(messageData));
        entity.setAppl_tot_ins_fee(verdatMapper.getApplTotInsFee(messageData));
        entity.setAppl_insr_financed(verdatMapper.getApplInsrFinanced(messageData));
        entity.setPaid_ins_fee(verdatMapper.getPaidInsFee(messageData));
        entity.setAppl_insr_buy_rate(verdatMapper.getApplInsrBuyRate(messageData));
        entity.setAppl_inst_amt(verdatMapper.getApplInstAmt(messageData));
        entity.setTot_ins_fee2(verdatMapper.getTotInsFee2(messageData));
        entity.setObjt_insr_financing_2(verdatMapper.getObjtInsrFinancing2(messageData));
        entity.setPaid_insr_fee2(verdatMapper.getPaidInsrFee2(messageData));
        entity.setTotal_provisi(verdatMapper.getTotalProvisi(messageData));
        entity.setProvisi_paid(verdatMapper.getProvisiPaid(messageData));
        entity.setProvisi_fin(verdatMapper.getProvisiFin(messageData));
        entity.setInstalment_amount(verdatMapper.getInstalmentAmount(messageData));
        entity.setCust_type(verdatMapper.getCustType(messageData));
        entity.setCust_no(verdatMapper.getCustNo(messageData));
        entity.setCust_sid_name(verdatMapper.getCustSidName(messageData));
        entity.setSex(verdatMapper.getSex(messageData));
        entity.setPhone_no(verdatMapper.getPhoneNo(messageData));
        entity.setDebitur_no_hp_1(verdatMapper.getDebiturNoHp1(messageData));
        entity.setCust_id_no(verdatMapper.getCustIdNo(messageData));
        entity.setMother_name(verdatMapper.getMotherName(messageData));
        entity.setCust_birth_date(verdatMapper.getCustBirthDate(messageData));
        entity.setCust_birth_place(verdatMapper.getCustBirthPlace(messageData));
        entity.setCust_monthly_income(verdatMapper.getCustMonthlyIncome(messageData));
        entity.setCust_address(verdatMapper.getCustAddress(messageData));
        entity.setRt(verdatMapper.getRt(messageData));
        entity.setRw(verdatMapper.getRw(messageData));
        entity.setCust_zip_code(verdatMapper.getCustZipCode(messageData));
        entity.setCust_kelurahan(verdatMapper.getCustKelurahan(messageData));
        entity.setCust_kecamatan(verdatMapper.getCustKecamatan(messageData));
        entity.setCust_kab_kota(verdatMapper.getCustKabKota(messageData));
        entity.setCust_provinsi(verdatMapper.getCustProvinsi(messageData));
        entity.setComp_name(verdatMapper.getCompName(messageData));
        entity.setComp_type(verdatMapper.getCompType(messageData));
        entity.setEconomic_sec1(verdatMapper.getEconomicSec1(messageData));
        entity.setEconomic_sec2(verdatMapper.getEconomicSec2(messageData));
        entity.setEconomic_sec3(verdatMapper.getEconomicSec3(messageData));
        entity.setNature_buss(verdatMapper.getNatureBuss(messageData));
        entity.setCust_curr_year_of_work(verdatMapper.getCustCurrYearOfWork(messageData));
        entity.setCom_status_tempat(verdatMapper.getComStatusTempat(messageData));
        entity.setCom_lokasi_usaha(verdatMapper.getComLokasiUsaha(messageData));
        entity.setCom_total_employee(verdatMapper.getComTotalEmployee(messageData));
        entity.setCom_no_of_year_buss(verdatMapper.getComNoOfYearBuss(messageData));
        entity.setCust_pro_lama_profesi(verdatMapper.getCustProLamaProfesi(messageData));
        entity.setJenis_profesi(verdatMapper.getJenisProfesi(messageData));
        // entity.setApproved_date(verdatMapper.getApprovedDate(messageData));
        entity.setStatus_appr(verdatMapper.getStatusAppr(messageData));
        // entity.setTanggal_cetak_po(verdatMapper.getTanggalCetakPo(messageData));
        entity.setApprove_note(verdatMapper.getApproveNote(messageData));
        // entity.setTanggal_fpd(verdatMapper.getTanggalFpd(messageData));
        entity.setNo_fpd(verdatMapper.getNoFpd(messageData));
        entity.setNpk_cmh(verdatMapper.getNpkCmh(messageData));
        entity.setNama_cmh(verdatMapper.getNamaCmh(messageData));
        entity.setInstallment_type(verdatMapper.getInstallmentType(messageData));
        entity.setAdvance_arrear(verdatMapper.getAdvanceArrear(messageData));
        entity.setTahun_kendaraan(verdatMapper.getTahunKendaraan(messageData));
        entity.setInsurance_fee(verdatMapper.getInsuranceFee(messageData));
        entity.setAppl_admf_komisi_amt(verdatMapper.getApplAdmfKomisiAmt(messageData));
        // entity.setStatus_cancel(verdatMapper.getStatusCancel(messageData));
        // entity.setCancel_pocl(verdatMapper.getCancelPocl(messageData));
        // entity.setMufnet(verdatMapper.getMufnet(messageData));
        entity.setPenggolongan_product(verdatMapper.getPenggolonganProduct(messageData));
        entity.setBank_wilayah_mdr(verdatMapper.getBankWilayahMdr(messageData));
        entity.setBank_area_mdr(verdatMapper.getBankAreaMdr(messageData));
        entity.setFlag_cancel(verdatMapper.getFlagCancel(messageData));
        // entity.setCancel_ppd_date(verdatMapper.getCancelPpdDate(messageData));
        entity.setStatus_repo(verdatMapper.getStatusRepo(messageData));
        entity.setNik_mca(verdatMapper.getNikMca(messageData));
        entity.setNama_mca(verdatMapper.getNamaMca(messageData));
        entity.setFirst_name(verdatMapper.getFirstName(messageData));
        entity.setLast_name(verdatMapper.getLastName(messageData));
        entity.setInsurance_type_code(verdatMapper.getInsuranceTypeCode(messageData));
        entity.setInsurance_type(verdatMapper.getInsuranceType(messageData));
        entity.setNama_bpkb(verdatMapper.getNamaBpkb(messageData));
        entity.setOccupation(verdatMapper.getOccupation(messageData));
        entity.setStatus_indent(verdatMapper.getStatusIndent(messageData));
        // entity.setCancel_reject_date_ca(verdatMapper.getCancelRejectDateCa(messageData));
        // entity.setCancel_reject_date_mkt(verdatMapper.getCancelRejectDateMkt(messageData));
        entity.setLtv(verdatMapper.getLtv(messageData));
        entity.setMarital(verdatMapper.getMarital(messageData));
        entity.setEducation(verdatMapper.getEducation(messageData));
        entity.setStatus_jf_bmri(verdatMapper.getStatusJfBmri(messageData));
        entity.setPrin_jf_bmri(verdatMapper.getPrinJfBmri(messageData));
        entity.setIntr_jf_bmri(verdatMapper.getIntrJfBmri(messageData));
        entity.setMkt_prod(verdatMapper.getMktProd(messageData));
        entity.setSumber_nasabah(verdatMapper.getSumberNasabah(messageData));
        entity.setProgramm(verdatMapper.getProgramm(messageData));
        entity.setEducation_code(verdatMapper.getEducationCode(messageData));
        entity.setOccupation_code(verdatMapper.getOccupationCode(messageData));
        entity.setEconomic_sector_code1(verdatMapper.getEconomicSectorCode1(messageData));
        entity.setEconomic_sector_code2(verdatMapper.getEconomicSectorCode2(messageData));
        entity.setEconomic_sector_code3(verdatMapper.getEconomicSectorCode3(messageData));
        entity.setRo_ao(verdatMapper.getRoAo(messageData));
        entity.setDsr(verdatMapper.getDsr(messageData));
        entity.setVehicle_type(verdatMapper.getVehicleType(messageData));
        entity.setDependent(verdatMapper.getDependent(messageData));
        entity.setLama_tinggal(verdatMapper.getLamaTinggal(messageData));
        entity.setBal_prin(verdatMapper.getBalPrin(messageData));
        entity.setOvd(verdatMapper.getOvd(messageData));
        entity.setFirst_installment_method(verdatMapper.getFirstInstallmentMethod(messageData));
        entity.setStatus_aging(verdatMapper.getStatusAging(messageData));
        entity.setSumber_data_desc(verdatMapper.getSumberDataDesc(messageData));
        entity.setSumber_order_desc(verdatMapper.getSumberOrderDesc(messageData));
        entity.setPortfolio_code(verdatMapper.getPortfolioCode(messageData));
        entity.setPortfolio_desc(verdatMapper.getPortfolioDesc(messageData));
        entity.setMogr_code(verdatMapper.getMogrCode(messageData));
        entity.setMogr_desc(verdatMapper.getMogrDesc(messageData));
        entity.setObmo_genre(verdatMapper.getObmoGenre(messageData));
        entity.setNpk_cmh_2(verdatMapper.getNpkCmh2(messageData));
        entity.setNama_cmh_2(verdatMapper.getNamaCmh2(messageData));
        entity.setTipe_restructuring(verdatMapper.getTipeRestructuring(messageData));
        entity.setNo_contract_old(verdatMapper.getNoContractOld(messageData));
        // entity.setScreening_1_date(verdatMapper.getScreening1Date(messageData));
        // entity.setScreening_2_date(verdatMapper.getScreening2Date(messageData));
        // entity.setInsert_date_reguler_survey(verdatMapper.getInsertDateRegulerSurvey(messageData));
        // entity.setScreening_3_date(verdatMapper.getScreening3Date(messageData));
        // entity.setNik_1(verdatMapper.getNik1(messageData));
        // entity.setNama_1(verdatMapper.getNama1(messageData));
        // entity.setJobcode_1(verdatMapper.getJobcode1(messageData));
        // entity.setResult_1(verdatMapper.getResult1(messageData));
        // entity.setDate_1(verdatMapper.getDate1(messageData));
        // entity.setNik_2(verdatMapper.getNik2(messageData));
        // entity.setNama_2(verdatMapper.getNama2(messageData));
        // entity.setJobcode_2(verdatMapper.getJobcode2(messageData));
        // entity.setResult_2(verdatMapper.getResult2(messageData));
        // entity.setDate_2(verdatMapper.getDate2(messageData));
        // entity.setNik_3(verdatMapper.getNik3(messageData));
        // entity.setNama_3(verdatMapper.getNama3(messageData));
        // entity.setJobcode_3(verdatMapper.getJobcode3(messageData));
        // entity.setResult_3(verdatMapper.getResult3(messageData));
        // entity.setDate_3(verdatMapper.getDate3(messageData));
        // entity.setNik_4(verdatMapper.getNik4(messageData));
        // entity.setNama_4(verdatMapper.getNama4(messageData));
        // entity.setJobcode_4(verdatMapper.getJobcode4(messageData));
        // entity.setResult_4(verdatMapper.getResult4(messageData));
        // entity.setDate_4(verdatMapper.getDate4(messageData));
        // entity.setNik_5(verdatMapper.getNik5(messageData));
        // entity.setNama_5(verdatMapper.getNama5(messageData));
        // entity.setJobcode_5(verdatMapper.getJobcode5(messageData));
        // entity.setResult_5(verdatMapper.getResult5(messageData));
        // entity.setDate_5(verdatMapper.getDate5(messageData));
        // entity.setNik_6(verdatMapper.getNik6(messageData));
        // entity.setNama_6(verdatMapper.getNama6(messageData));
        // entity.setJobcode_6(verdatMapper.getJobcode6(messageData));
        // entity.setResult_6(verdatMapper.getResult6(messageData));
        // entity.setDate_6(verdatMapper.getDate6(messageData));
        // entity.setNik_7(verdatMapper.getNik7(messageData));
        // entity.setNama_7(verdatMapper.getNama7(messageData));
        // entity.setJobcode_7(verdatMapper.getJobcode7(messageData));
        // entity.setResult_7(verdatMapper.getResult7(messageData));
        // entity.setDate_7(verdatMapper.getDate7(messageData));
        // entity.setNik_8(verdatMapper.getNik8(messageData));
        // entity.setNama_8(verdatMapper.getNama8(messageData));
        // entity.setJobcode_8(verdatMapper.getJobcode8(messageData));
        // entity.setResult_8(verdatMapper.getResult8(messageData));
        // entity.setDate_8(verdatMapper.getDate8(messageData));
        // entity.setNik_9(verdatMapper.getNik9(messageData));
        // entity.setNama_9(verdatMapper.getNama9(messageData));
        // entity.setJobcode_9(verdatMapper.getJobcode9(messageData));
        // entity.setResult_9(verdatMapper.getResult9(messageData));
        // entity.setDate_9(verdatMapper.getDate9(messageData));
        // entity.setNik_10(verdatMapper.getNik10(messageData));
        // entity.setNama_10(verdatMapper.getNama10(messageData));
        // entity.setJobcode_10(verdatMapper.getJobcode10(messageData));
        // entity.setResult_10(verdatMapper.getResult10(messageData));
        // entity.setDate_10(verdatMapper.getDate10(messageData));
        // entity.setNik_11(verdatMapper.getNik11(messageData));
        // entity.setNama_11(verdatMapper.getNama11(messageData));
        // entity.setJobcode_11(verdatMapper.getJobcode11(messageData));
        // entity.setResult_11(verdatMapper.getResult11(messageData));
        // entity.setDate_11(verdatMapper.getDate11(messageData));
        // entity.setNik_12(verdatMapper.getNik12(messageData));
        // entity.setNama_12(verdatMapper.getNama12(messageData));
        // entity.setJobcode_12(verdatMapper.getJobcode12(messageData));
        // entity.setResult_12(verdatMapper.getResult12(messageData));
        // entity.setDate_12(verdatMapper.getDate12(messageData));
        // entity.setNik_13(verdatMapper.getNik13(messageData));
        // entity.setNama_13(verdatMapper.getNama13(messageData));
        // entity.setJobcode_13(verdatMapper.getJobcode13(messageData));
        // entity.setResult_13(verdatMapper.getResult13(messageData));
        // entity.setDate_13(verdatMapper.getDate13(messageData));
        // entity.setNik_14(verdatMapper.getNik14(messageData));
        // entity.setNama_14(verdatMapper.getNama14(messageData));
        // entity.setJobcode_14(verdatMapper.getJobcode14(messageData));
        // entity.setResult_14(verdatMapper.getResult14(messageData));
        // entity.setDate_14(verdatMapper.getDate14(messageData));
        // entity.setNik_15(verdatMapper.getNik15(messageData));
        // entity.setNama_15(verdatMapper.getNama15(messageData));
        // entity.setJobcode_15(verdatMapper.getJobcode15(messageData));
        // entity.setResult_15(verdatMapper.getResult15(messageData));
        // entity.setDate_15(verdatMapper.getDate15(messageData));
        // entity.setDate_cancel_reguler(verdatMapper.getDateCancelReguler(messageData));
        // entity.setDate_cancel_pocl(verdatMapper.getDateCancelPocl(messageData));
        // entity.setInsert_date_pocl(verdatMapper.getInsertDatePocl(messageData));
        // entity.setPrint_date_pocl(verdatMapper.getPrintDatePocl(messageData));
        // entity.setDate_full_data_entry(verdatMapper.getDateFullDataEntry(messageData));
        entity.setCancel_todolist(verdatMapper.getCancelTodolist(messageData));
        // entity.setDate_cancel_kyc(verdatMapper.getDateCancelKyc(messageData));
        entity.setFin_prod_desc(verdatMapper.getFinProdDesc(messageData));
        entity.setFin_purpose_desc(verdatMapper.getFinPurposeDesc(messageData));
        entity.setNature_of_financing(verdatMapper.getNatureOfFinancing(messageData));
        entity.setInitial_1(verdatMapper.getInitial1(messageData));
        entity.setOutlet(verdatMapper.getOutlet(messageData));
        entity.setInternal_sales_force2_code(verdatMapper.getInternalSalesForce2Code(messageData));
        entity.setInternal_sales_force2_nik(verdatMapper.getInternalSalesForce2Nik(messageData));
        entity.setInternal_sales_force2_name(verdatMapper.getInternalSalesForce2Name(messageData));
        entity.setInternal_sales_force2_job(verdatMapper.getInternalSalesForce2Job(messageData));
        entity.setInitial_2(verdatMapper.getInitial2(messageData));
        entity.setPengajuan_telesurvey(verdatMapper.getPengajuanTelesurvey(messageData));
        entity.setProses_pembiayaan_telesurvey(verdatMapper.getProsesPembiayaanTelesurvey(messageData));
        entity.setDate_telesurvey(verdatMapper.getDateTelesurvey(messageData));
        // entity.setInsert_by_telesurvey(verdatMapper.getInsertByTelesurvey(messageData));
        entity.setStatus_kyc(verdatMapper.getStatusKyc(messageData));
        // entity.setDate_kyc(verdatMapper.getDateKyc(messageData));
        // entity.setInsert_by_kyc(verdatMapper.getInsertByKyc(messageData));
        entity.setHasil_kyc(verdatMapper.getHasilKyc(messageData));
        entity.setArea_id(verdatMapper.getAreaId(messageData));
        // entity.setInsert_date(verdatMapper.getInsertDate(messageData));
        // entity.setUpdate_date(verdatMapper.getUpdateDate(messageData));
        entity.setAsuransi_kendaraan(verdatMapper.getAsuransiKendaraan(messageData));
        entity.setAsuransi_tambahan(verdatMapper.getAsuransiTambahan(messageData));
        entity.setEng_capacity(verdatMapper.getEngCapacity(messageData));
        entity.setSkema_pembiayaan(verdatMapper.getSkemaPembiayaan(messageData));
        entity.setTotal_interest_amount(verdatMapper.getTotalInterestAmount(messageData));
        entity.setInsurance_credit_fee(verdatMapper.getInsuranceCreditFee(messageData));
        entity.setJatuh_tempo(verdatMapper.getJatuhTempo(messageData));
        entity.setObj_pembiayaan(verdatMapper.getObjPembiayaan(messageData));
        entity.setInternal_sales_head(verdatMapper.getInternalSalesHead(messageData));
        entity.setFin_scheme_code(verdatMapper.getFinSchemeCode(messageData));
        entity.setNo_obligor_id(verdatMapper.getNoObligorId(messageData));
        entity.setNo_po_cl(verdatMapper.getNoPoCl(messageData));
        entity.setInterest_amount(verdatMapper.getInterestAmount(messageData));
        entity.setBiaya_asuransi_tambahan(verdatMapper.getBiayaAsuransiTambahan(messageData));
        // entity.setJob_internal_sales_forced(verdatMapper.getJobInternalSalesForced(messageData));
        // entity.setNama_internal_sales_forced(verdatMapper.getNamaInternalSalesForced(messageData));
        entity.setKeterangan_po(verdatMapper.getKeteranganPo(messageData));
        entity.setNilai_pelunasan(verdatMapper.getNilaiPelunasan(messageData));
        entity.setAlasan_cancel_po_cl(verdatMapper.getAlasanCancelPoCl(messageData));
        entity.setNotes_cancel_po_cl(verdatMapper.getNotesCancelPoCl(messageData));
        entity.setNik_reject_cancel_marketing(verdatMapper.getNikRejectCancelMarketing(messageData));
        entity.setUser_reject_cancel_marketing(verdatMapper.getUserRejectCancelMarketing(messageData));
        entity.setPic_dealer(verdatMapper.getPicDealer(messageData));
        entity.setFlagging_reject_cancel_mkt(verdatMapper.getFlaggingRejectCancelMkt(messageData));
        entity.setDeskripsi_reject_cancel_mkt(verdatMapper.getDeskripsiRejectCancelMkt(messageData));
        entity.setAlasan_reject_cancel_mkt(verdatMapper.getAlasanRejectCancelMkt(messageData));
        entity.setReject_cancel_source_app(verdatMapper.getRejectCancelSourceApp(messageData));
        // entity.setDeskripsi_source_aplikasi(verdatMapper.getDeskripsiSourceAplikasi(messageData));
        entity.setAlasan_koreksi_po(verdatMapper.getAlasanKoreksiPo(messageData));
        entity.setNik_koreksi_po(verdatMapper.getNikKoreksiPo(messageData));
        // entity.setTanggal_koreksi_po(verdatMapper.getTanggalKoreksiPo(messageData));
        entity.setTotal_koreksi_po(verdatMapper.getTotalKoreksiPo(messageData));
        // entity.setCara_bayar_angsuran(verdatMapper.getCaraBayarAngsuran(messageData));
        entity.setStatus_aplikasi(verdatMapper.getStatusAplikasi(messageData));
        entity.setJumlah_nasabah_ditolak(verdatMapper.getJumlahNasabahDitolak(messageData));
        entity.setJumlah_cetak_po_cl(verdatMapper.getJumlahCetakPoCl(messageData));
        entity.setJumlah_po_cl_belum_cetak(verdatMapper.getJumlahPoClBelumCetak(messageData));
        entity.setJumlah_cancel_po_cl(verdatMapper.getJumlahCancelPoCl(messageData));
        entity.setJumlah_koreksi_po_cl(verdatMapper.getJumlahKoreksiPoCl(messageData));
        entity.setJumlah_po_cl_pending(verdatMapper.getJumlahPoClPending(messageData));
        entity.setJumlah_nasabah_cancel_ppd(verdatMapper.getJumlahNasabahCancelPpd(messageData));
        entity.setJumlah_tagihan_belum_ppd(verdatMapper.getJumlahTagihanBelumPpd(messageData));
        entity.setJumlah_reject_cancel_marketing(verdatMapper.getJumlahRejectCancelMarketing(messageData));
        // entity.setTipe_debitur(verdatMapper.getTipeDebitur(messageData));
        // entity.setTanggal_entry(verdatMapper.getTanggalEntry(messageData));
        // entity.setTanggal_approval(verdatMapper.getTanggalApproval(messageData));
        // entity.setTanggal_cetak(verdatMapper.getTanggalCetak(messageData));
        // entity.setTanggal_cancel(verdatMapper.getTanggalCancel(messageData));
        // entity.setTanggal_koreksi(verdatMapper.getTanggalKoreksi(messageData));
    }

}
