server:
  port: 9999

spring:
  application:
    name: datalake_subscriber_java

  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: test
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    topic:
      # result_verifikasi_data: result_verifikasi_data
      test-datalake: test-datalake
      test-regsur: test-regsur
      test-verdat: test-verdat
      test-preppd: test-preppd

  datasource:
    url: jdbc:postgresql://localhost:5432/datalake
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  # datasource:
  #   url: jdbc:postgresql://10.22.15.124:5432/reporting?assumeMinServerVersion=9.4?ApplicationName=datalake_report
  #   username: dev_revamp
  #   password: dev_2021
  #   driver-class-name: org.postgresql.Driver

  jpa:
    # show-sql: true
    hibernate:
      ddl-auto: update
      # format_sql: true
