package com.datalake.datalake_subscriber_java.processors;

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.datalake.datalake_subscriber_java.entities.DatalakeEntity;
import com.datalake.datalake_subscriber_java.extractors.VerdatDataExtractor;
import com.datalake.datalake_subscriber_java.repositories.DatalakeRepository;
import com.datalake.datalake_subscriber_java.utilities.JsonUtility;

@Component("test-datalake")
public class VerdatProcessor implements TopicProcessor {

    @Autowired
    private static Logger logger = LoggerFactory.getLogger(VerdatProcessor.class);

    @Autowired
    private DatalakeRepository datalakeRepository;

    @Autowired
    private JsonUtility jsonUtility;

    @Autowired
    private VerdatDataExtractor verdatData;

    @Override
    // @Transactional
    public void process(String message) {
        Map<String, Object> messageData = jsonUtility.parseMessage(message);
        String order_id = verdatData.getOrderId(messageData);

        if (order_id == null || order_id.isEmpty()) {
            logger.warn("Order ID is null or empty.");
            return;
        }

        DatalakeEntity entity = createOrUpdateEntity(messageData, order_id);
        saveEntity(entity);
        ;

    }

    private DatalakeEntity createOrUpdateEntity(Map<String, Object> messageData, String order_id) {
        DatalakeEntity entity = datalakeRepository.findByOrder_id(order_id);
        String currentForm = "VERDAT";
        if (entity == null) {
            entity = new DatalakeEntity();
            entity.setOrder_id(order_id);
            logger.info("Entity created: Order ID = {}, Current Form = {}", order_id, currentForm);
        } else {
            logger.info("Entity found for update: Order ID = {}, Current Form = {}", order_id, currentForm);
        }

        updateEntityFromMessage(entity, messageData);
        return entity;
    }

    private void updateEntityFromMessage(DatalakeEntity entity, Map<String, Object> messageData) {
        entity.setOrder_id(verdatData.getOrderId(messageData));
        entity.setCurrent_form_desc(verdatData.getCurrentFormDesc(messageData));
        entity.setAppl_no(verdatData.getApplNo(messageData));
        entity.setAppl_date(verdatData.getApplDate(messageData));
        entity.setOrder_date(verdatData.getOrderDate(messageData));
        entity.setAppl_contract_no(verdatData.getApplContractNo(messageData));
        entity.setMax_approval(verdatData.getMaxApproval(messageData));
        entity.setLast_approval(verdatData.getLastApproval(messageData));
        entity.setMax_deviasi(verdatData.getMaxDeviasi(messageData));
        entity.setAppl_ppd_date(verdatData.getApplPpdDate(messageData));
        entity.setFin_type(verdatData.getFinType(messageData));
        entity.setFinance_product(verdatData.getFinanceProduct(messageData));
        entity.setCore_product(verdatData.getCoreProduct(messageData));
        entity.setArea(verdatData.getArea(messageData));
        entity.setBran_br_name(verdatData.getBranBrName(messageData));
        entity.setBran_br_id(verdatData.getBranBrId(messageData));
        entity.setOutlet_channel_desc(verdatData.getOutletChannelDesc(messageData));
        entity.setAppl_sales_through(verdatData.getApplSalesThrough(messageData));
        entity.setSales_throught(verdatData.getSalesThrought(messageData));
        entity.setInitiall(verdatData.getInitiall(messageData));
        entity.setInternal_sales_force_code(verdatData.getInternalSalesForceCode(messageData));
        entity.setInternal_sales_force_nik(verdatData.getInternalSalesForceNik(messageData));
        entity.setInternal_sales_force_name(verdatData.getInternalSalesForceName(messageData));
        entity.setInternal_sales_force_job(verdatData.getInternalSalesForceJob(messageData));
        entity.setInterxt_sales_force1_name(verdatData.getInterxtSalesForce1Name(messageData));
        entity.setInterxt_sales_force1_npk(verdatData.getInterxtSalesForce1Npk(messageData));
        entity.setInterxt_sales_force1_job(verdatData.getInterxtSalesForce1Job(messageData));
        entity.setInterxt_sales_force2_name(verdatData.getInterxtSalesForce2Name(messageData));
        entity.setInterxt_sales_force2_npk(verdatData.getInterxtSalesForce2Npk(messageData));
        entity.setInterxt_sales_force2_job(verdatData.getInterxtSalesForce2Job(messageData));
        entity.setId_empl_mitra(verdatData.getIdEmplMitra(messageData));
        entity.setCompany(verdatData.getCompany(messageData));
        entity.setEmpl_nik_bank(verdatData.getEmplNikBank(messageData));
        entity.setNo_telephone(verdatData.getNoTelephone(messageData));
        entity.setBank_branch_id(verdatData.getBankBranchId(messageData));
        entity.setBank_office_location(verdatData.getBankOfficeLocation(messageData));
        entity.setKode_pekerjaan(verdatData.getKodePekerjaan(messageData));
        entity.setDebitur_no_npwp(verdatData.getDebiturNoNpwp(messageData));
        entity.setNpwp_type(verdatData.getNpwpType(messageData));
        entity.setBank_deal_empl(verdatData.getBankDealEmpl(messageData));
        entity.setEmpl_acc_no(verdatData.getEmplAccNo(messageData));
        entity.setEmpl_addr(verdatData.getEmplAddr(messageData));
        entity.setDlc(verdatData.getDlc(messageData));
        entity.setCred_deal_name(verdatData.getCredDealName(messageData));
        entity.setAppl_appl_tag1(verdatData.getApplApplTag1(messageData));
        entity.setAplication_tag1_desc(verdatData.getAplicationTag1Desc(messageData));
        entity.setAppl_appl_tag2(verdatData.getApplApplTag2(messageData));
        entity.setAplication_tax2_desc(verdatData.getAplicationTax2Desc(messageData));
        entity.setAppl_appl_tag3(verdatData.getApplApplTag3(messageData));
        entity.setAplication_tax3_desc(verdatData.getAplicationTax3Desc(messageData));
        entity.setStatus(verdatData.getStatus(messageData));
        entity.setAppl_objt_code(verdatData.getApplObjtCode(messageData));
        entity.setObjt_desc(verdatData.getObjtDesc(messageData));
        entity.setObbr_code(verdatData.getObbrCode(messageData));
        entity.setObbr_desc(verdatData.getObbrDesc(messageData));
        entity.setBahan_bakar(verdatData.getBahanBakar(messageData));
        entity.setObty_code(verdatData.getObtyCode(messageData));
        entity.setObty_desc(verdatData.getObtyDesc(messageData));
        entity.setObmo_code(verdatData.getObmoCode(messageData));
        entity.setObmo_desc(verdatData.getObmoDesc(messageData));
        entity.setObjt_obj_year(verdatData.getObjtObjYear(messageData));
        entity.setObjt_obj_mfg_year(verdatData.getObjtObjMfgYear(messageData));
        entity.setObjt_color(verdatData.getObjtColor(messageData));
        entity.setObjt_frame_no(verdatData.getObjtFrameNo(messageData));
        entity.setObjt_engine_no(verdatData.getObjtEngineNo(messageData));
        entity.setPurpose_desc(verdatData.getPurposeDesc(messageData));
        entity.setPaym_type_desc(verdatData.getPaymTypeDesc(messageData));
        entity.setBank_name(verdatData.getBankName(messageData));
        entity.setAppl_autodebit_acc_no(verdatData.getApplAutodebitAccNo(messageData));
        entity.setAppl_autodebit_acc_name(verdatData.getApplAutodebitAccName(messageData));
        entity.setAppl_mkpp_id(verdatData.getApplMkppId(messageData));
        entity.setMkpp_desc(verdatData.getMkppDesc(messageData));
        entity.setSubsidi_dp(verdatData.getSubsidiDp(messageData));
        entity.setJoint_promo(verdatData.getJointPromo(messageData));
        entity.setAdm_from_deal(verdatData.getAdmFromDeal(messageData));
        entity.setBbm_from_deal(verdatData.getBbmFromDeal(messageData));
        entity.setSubs_potong_pelunasan(verdatData.getSubsPotongPelunasan(messageData));
        entity.setSubsidi_klaim(verdatData.getSubsidiKlaim(messageData));
        entity.setDisc_kom(verdatData.getDiscKom(messageData));
        entity.setDiscount(verdatData.getDiscount(messageData));
        entity.setKomisi_langsung(verdatData.getKomisiLangsung(messageData));
        entity.setAdm_from_mu(verdatData.getAdmFromMu(messageData));
        entity.setBbm_from_mu(verdatData.getBbmFromMu(messageData));
        entity.setAppl_principal_amt(verdatData.getApplPrincipalAmt(messageData));
        entity.setPrin_plus_intr_amount(verdatData.getPrinPlusIntrAmount(messageData));
        entity.setAppl_top(verdatData.getApplTop(messageData));
        entity.setTot_adm_fee(verdatData.getTotAdmFee(messageData));
        entity.setAdm_fin(verdatData.getAdmFin(messageData));
        entity.setAdm_fee(verdatData.getAdmFee(messageData));
        entity.setOtr(verdatData.getOtr(messageData));
        entity.setAppl_adm_fee(verdatData.getApplAdmFee(messageData));
        entity.setAppl_gross_dp(verdatData.getApplGrossDp(messageData));
        entity.setAppl_net_dp(verdatData.getApplNetDp(messageData));
        entity.setDp_branch(verdatData.getDpBranch(messageData));
        entity.setAppl_int_flat_rate(verdatData.getApplIntFlatRate(messageData));
        entity.setAppl_int_eff_rate(verdatData.getApplIntEffRate(messageData));
        entity.setAppl_tot_ins_fee(verdatData.getApplTotInsFee(messageData));
        entity.setAppl_insr_financed(verdatData.getApplInsrFinanced(messageData));
        entity.setPaid_ins_fee(verdatData.getPaidInsFee(messageData));
        entity.setAppl_insr_buy_rate(verdatData.getApplInsrBuyRate(messageData));
        entity.setAppl_inst_amt(verdatData.getApplInstAmt(messageData));
        entity.setTot_ins_fee2(verdatData.getTotInsFee2(messageData));
        entity.setObjt_insr_financing_2(verdatData.getObjtInsrFinancing2(messageData));
        entity.setPaid_insr_fee2(verdatData.getPaidInsrFee2(messageData));
        entity.setTotal_provisi(verdatData.getTotalProvisi(messageData));
        entity.setProvisi_paid(verdatData.getProvisiPaid(messageData));
        entity.setProvisi_fin(verdatData.getProvisiFin(messageData));
        entity.setInstalment_amount(verdatData.getInstalmentAmount(messageData));
        entity.setCust_type(verdatData.getCustType(messageData));
        entity.setCust_no(verdatData.getCustNo(messageData));
        entity.setCust_sid_name(verdatData.getCustSidName(messageData));
        entity.setSex(verdatData.getSex(messageData));
        entity.setPhone_no(verdatData.getPhoneNo(messageData));
        entity.setDebitur_no_hp_1(verdatData.getDebiturNoHp1(messageData));
        entity.setCust_id_no(verdatData.getCustIdNo(messageData));
        entity.setMother_name(verdatData.getMotherName(messageData));
        entity.setCust_birth_date(verdatData.getCustBirthDate(messageData));
        entity.setCust_birth_place(verdatData.getCustBirthPlace(messageData));
        entity.setCust_monthly_income(verdatData.getCustMonthlyIncome(messageData));
        entity.setCust_address(verdatData.getCustAddress(messageData));
        entity.setRt(verdatData.getRt(messageData));
        entity.setRw(verdatData.getRw(messageData));
        entity.setCust_zip_code(verdatData.getCustZipCode(messageData));
        entity.setCust_kelurahan(verdatData.getCustKelurahan(messageData));
        entity.setCust_kecamatan(verdatData.getCustKecamatan(messageData));
        entity.setCust_kab_kota(verdatData.getCustKabKota(messageData));
        entity.setCust_provinsi(verdatData.getCustProvinsi(messageData));
        entity.setComp_name(verdatData.getCompName(messageData));
        entity.setComp_type(verdatData.getCompType(messageData));
        entity.setEconomic_sec1(verdatData.getEconomicSec1(messageData));
        entity.setEconomic_sec2(verdatData.getEconomicSec2(messageData));
        entity.setEconomic_sec3(verdatData.getEconomicSec3(messageData));
        entity.setNature_buss(verdatData.getNatureBuss(messageData));
        entity.setCust_curr_year_of_work(verdatData.getCustCurrYearOfWork(messageData));
        entity.setCom_status_tempat(verdatData.getComStatusTempat(messageData));
        entity.setCom_lokasi_usaha(verdatData.getComLokasiUsaha(messageData));
        entity.setCom_total_employee(verdatData.getComTotalEmployee(messageData));
        entity.setCom_no_of_year_buss(verdatData.getComNoOfYearBuss(messageData));
        entity.setCust_pro_lama_profesi(verdatData.getCustProLamaProfesi(messageData));
        entity.setJenis_profesi(verdatData.getJenisProfesi(messageData));
        entity.setApproved_date(verdatData.getApprovedDate(messageData));
        entity.setStatus_appr(verdatData.getStatusAppr(messageData));
        entity.setTanggal_cetak_po(verdatData.getTanggalCetakPo(messageData));
        entity.setApprove_note(verdatData.getApproveNote(messageData));
        entity.setTanggal_fpd(verdatData.getTanggalFpd(messageData));
        entity.setNo_fpd(verdatData.getNoFpd(messageData));
        entity.setNpk_cmh(verdatData.getNpkCmh(messageData));
        entity.setNama_cmh(verdatData.getNamaCmh(messageData));
        entity.setInstallment_type(verdatData.getInstallmentType(messageData));
        entity.setAdvance_arrear(verdatData.getAdvanceArrear(messageData));
        entity.setTahun_kendaraan(verdatData.getTahunKendaraan(messageData));
        entity.setInsurance_fee(verdatData.getInsuranceFee(messageData));
        entity.setAppl_admf_komisi_amt(verdatData.getApplAdmfKomisiAmt(messageData));
        entity.setStatus_cancel(verdatData.getStatusCancel(messageData));
        entity.setCancel_pocl(verdatData.getCancelPocl(messageData));
        entity.setMufnet(verdatData.getMufnet(messageData));
        entity.setPenggolongan_product(verdatData.getPenggolonganProduct(messageData));
        entity.setBank_wilayah_mdr(verdatData.getBankWilayahMdr(messageData));
        entity.setBank_area_mdr(verdatData.getBankAreaMdr(messageData));
        entity.setFlag_cancel(verdatData.getFlagCancel(messageData));
        entity.setCancel_ppd_date(verdatData.getCancelPpdDate(messageData));
        entity.setStatus_repo(verdatData.getStatusRepo(messageData));
        entity.setNik_mca(verdatData.getNikMca(messageData));
        entity.setNama_mca(verdatData.getNamaMca(messageData));
        entity.setFirst_name(verdatData.getFirstName(messageData));
        entity.setLast_name(verdatData.getLastName(messageData));
        entity.setInsurance_type_code(verdatData.getInsuranceTypeCode(messageData));
        entity.setInsurance_type(verdatData.getInsuranceType(messageData));
        entity.setNama_bpkb(verdatData.getNamaBpkb(messageData));
        entity.setOccupation(verdatData.getOccupation(messageData));
        entity.setStatus_indent(verdatData.getStatusIndent(messageData));
        entity.setCancel_reject_date_ca(verdatData.getCancelRejectDateCa(messageData));
        entity.setCancel_reject_date_mkt(verdatData.getCancelRejectDateMkt(messageData));
        entity.setLtv(verdatData.getLtv(messageData));
        entity.setMarital(verdatData.getMarital(messageData));
        entity.setEducation(verdatData.getEducation(messageData));
        entity.setStatus_jf_bmri(verdatData.getStatusJfBmri(messageData));
        entity.setPrin_jf_bmri(verdatData.getPrinJfBmri(messageData));
        entity.setIntr_jf_bmri(verdatData.getIntrJfBmri(messageData));
        entity.setMkt_prod(verdatData.getMktProd(messageData));
        entity.setSumber_nasabah(verdatData.getSumberNasabah(messageData));
        entity.setProgramm(verdatData.getProgramm(messageData));
        entity.setEducation_code(verdatData.getEducationCode(messageData));
        entity.setOccupation_code(verdatData.getOccupationCode(messageData));
        entity.setEconomic_sector_code1(verdatData.getEconomicSectorCode1(messageData));
        entity.setEconomic_sector_code2(verdatData.getEconomicSectorCode2(messageData));
        entity.setEconomic_sector_code3(verdatData.getEconomicSectorCode3(messageData));
        entity.setRo_ao(verdatData.getRoAo(messageData));
        entity.setDsr(verdatData.getDsr(messageData));
        entity.setVehicle_type(verdatData.getVehicleType(messageData));
        entity.setDependent(verdatData.getDependent(messageData));
        entity.setLama_tinggal(verdatData.getLamaTinggal(messageData));
        entity.setBal_prin(verdatData.getBalPrin(messageData));
        entity.setOvd(verdatData.getOvd(messageData));
        entity.setFirst_installment_method(verdatData.getFirstInstallmentMethod(messageData));
        entity.setStatus_aging(verdatData.getStatusAging(messageData));
        entity.setSumber_data_desc(verdatData.getSumberDataDesc(messageData));
        entity.setSumber_order_desc(verdatData.getSumberOrderDesc(messageData));
        entity.setPortfolio_code(verdatData.getPortfolioCode(messageData));
        entity.setPortfolio_desc(verdatData.getPortfolioDesc(messageData));
        entity.setMogr_code(verdatData.getMogrCode(messageData));
        entity.setMogr_desc(verdatData.getMogrDesc(messageData));
        entity.setObmo_genre(verdatData.getObmoGenre(messageData));
        entity.setNpk_cmh_2(verdatData.getNpkCmh2(messageData));
        entity.setNama_cmh_2(verdatData.getNamaCmh2(messageData));
        entity.setTipe_restructuring(verdatData.getTipeRestructuring(messageData));
        entity.setNo_contract_old(verdatData.getNoContractOld(messageData));
        entity.setScreening_1_date(verdatData.getScreening1Date(messageData));
        entity.setScreening_2_date(verdatData.getScreening2Date(messageData));
        entity.setInsert_date_reguler_survey(verdatData.getInsertDateRegulerSurvey(messageData));
        entity.setScreening_3_date(verdatData.getScreening3Date(messageData));
        entity.setNik_1(verdatData.getNik1(messageData));
        entity.setNama_1(verdatData.getNama1(messageData));
        entity.setJobcode_1(verdatData.getJobcode1(messageData));
        entity.setResult_1(verdatData.getResult1(messageData));
        entity.setDate_1(verdatData.getDate1(messageData));
        entity.setNik_2(verdatData.getNik2(messageData));
        entity.setNama_2(verdatData.getNama2(messageData));
        entity.setJobcode_2(verdatData.getJobcode2(messageData));
        entity.setResult_2(verdatData.getResult2(messageData));
        entity.setDate_2(verdatData.getDate2(messageData));
        entity.setNik_3(verdatData.getNik3(messageData));
        entity.setNama_3(verdatData.getNama3(messageData));
        entity.setJobcode_3(verdatData.getJobcode3(messageData));
        entity.setResult_3(verdatData.getResult3(messageData));
        entity.setDate_3(verdatData.getDate3(messageData));
        entity.setNik_4(verdatData.getNik4(messageData));
        entity.setNama_4(verdatData.getNama4(messageData));
        entity.setJobcode_4(verdatData.getJobcode4(messageData));
        entity.setResult_4(verdatData.getResult4(messageData));
        entity.setDate_4(verdatData.getDate4(messageData));
        entity.setNik_5(verdatData.getNik5(messageData));
        entity.setNama_5(verdatData.getNama5(messageData));
        entity.setJobcode_5(verdatData.getJobcode5(messageData));
        entity.setResult_5(verdatData.getResult5(messageData));
        entity.setDate_5(verdatData.getDate5(messageData));
        entity.setNik_6(verdatData.getNik6(messageData));
        entity.setNama_6(verdatData.getNama6(messageData));
        entity.setJobcode_6(verdatData.getJobcode6(messageData));
        entity.setResult_6(verdatData.getResult6(messageData));
        entity.setDate_6(verdatData.getDate6(messageData));
        entity.setNik_7(verdatData.getNik7(messageData));
        entity.setNama_7(verdatData.getNama7(messageData));
        entity.setJobcode_7(verdatData.getJobcode7(messageData));
        entity.setResult_7(verdatData.getResult7(messageData));
        entity.setDate_7(verdatData.getDate7(messageData));
        entity.setNik_8(verdatData.getNik8(messageData));
        entity.setNama_8(verdatData.getNama8(messageData));
        entity.setJobcode_8(verdatData.getJobcode8(messageData));
        entity.setResult_8(verdatData.getResult8(messageData));
        entity.setDate_8(verdatData.getDate8(messageData));
        entity.setNik_9(verdatData.getNik9(messageData));
        entity.setNama_9(verdatData.getNama9(messageData));
        entity.setJobcode_9(verdatData.getJobcode9(messageData));
        entity.setResult_9(verdatData.getResult9(messageData));
        entity.setDate_9(verdatData.getDate9(messageData));
        entity.setNik_10(verdatData.getNik10(messageData));
        entity.setNama_10(verdatData.getNama10(messageData));
        entity.setJobcode_10(verdatData.getJobcode10(messageData));
        entity.setResult_10(verdatData.getResult10(messageData));
        entity.setDate_10(verdatData.getDate10(messageData));
        entity.setNik_11(verdatData.getNik11(messageData));
        entity.setNama_11(verdatData.getNama11(messageData));
        entity.setJobcode_11(verdatData.getJobcode11(messageData));
        entity.setResult_11(verdatData.getResult11(messageData));
        entity.setDate_11(verdatData.getDate11(messageData));
        entity.setNik_12(verdatData.getNik12(messageData));
        entity.setNama_12(verdatData.getNama12(messageData));
        entity.setJobcode_12(verdatData.getJobcode12(messageData));
        entity.setResult_12(verdatData.getResult12(messageData));
        entity.setDate_12(verdatData.getDate12(messageData));
        entity.setNik_13(verdatData.getNik13(messageData));
        entity.setNama_13(verdatData.getNama13(messageData));
        entity.setJobcode_13(verdatData.getJobcode13(messageData));
        entity.setResult_13(verdatData.getResult13(messageData));
        entity.setDate_13(verdatData.getDate13(messageData));
        entity.setNik_14(verdatData.getNik14(messageData));
        entity.setNama_14(verdatData.getNama14(messageData));
        entity.setJobcode_14(verdatData.getJobcode14(messageData));
        entity.setResult_14(verdatData.getResult14(messageData));
        entity.setDate_14(verdatData.getDate14(messageData));
        entity.setNik_15(verdatData.getNik15(messageData));
        entity.setNama_15(verdatData.getNama15(messageData));
        entity.setJobcode_15(verdatData.getJobcode15(messageData));
        entity.setResult_15(verdatData.getResult15(messageData));
        entity.setDate_15(verdatData.getDate15(messageData));
        entity.setDate_cancel_reguler(verdatData.getDateCancelReguler(messageData));
        entity.setDate_cancel_pocl(verdatData.getDateCancelPocl(messageData));
        entity.setInsert_date_pocl(verdatData.getInsertDatePocl(messageData));
        entity.setPrint_date_pocl(verdatData.getPrintDatePocl(messageData));
        entity.setDate_full_data_entry(verdatData.getDateFullDataEntry(messageData));
        entity.setCancel_todolist(verdatData.getCancelTodolist(messageData));
        entity.setDate_cancel_kyc(verdatData.getDateCancelKyc(messageData));
        entity.setFin_prod_desc(verdatData.getFinProdDesc(messageData));
        entity.setFin_purpose_desc(verdatData.getFinPurposeDesc(messageData));
        entity.setNature_of_financing(verdatData.getNatureOfFinancing(messageData));
        entity.setInitial_1(verdatData.getInitial1(messageData));
        entity.setOutlet(verdatData.getOutlet(messageData));
        entity.setInternal_sales_force2_code(verdatData.getInternalSalesForce2Code(messageData));
        entity.setInternal_sales_force2_nik(verdatData.getInternalSalesForce2Nik(messageData));
        entity.setInternal_sales_force2_name(verdatData.getInternalSalesForce2Name(messageData));
        entity.setInternal_sales_force2_job(verdatData.getInternalSalesForce2Job(messageData));
        entity.setInitial_2(verdatData.getInitial2(messageData));
        entity.setPengajuan_telesurvey(verdatData.getPengajuanTelesurvey(messageData));
        entity.setProses_pembiayaan_telesurvey(verdatData.getProsesPembiayaanTelesurvey(messageData));
        entity.setDate_telesurvey(verdatData.getDateTelesurvey(messageData));
        entity.setInsert_by_telesurvey(verdatData.getInsertByTelesurvey(messageData));
        entity.setStatus_kyc(verdatData.getStatusKyc(messageData));
        entity.setDate_kyc(verdatData.getDateKyc(messageData));
        entity.setInsert_by_kyc(verdatData.getInsertByKyc(messageData));
        entity.setHasil_kyc(verdatData.getHasilKyc(messageData));
        entity.setArea_id(verdatData.getAreaId(messageData));
        entity.setInsert_date(verdatData.getInsertDate(messageData));
        entity.setUpdate_date(verdatData.getUpdateDate(messageData));
        entity.setAsuransi_kendaraan(verdatData.getAsuransiKendaraan(messageData));
        entity.setAsuransi_tambahan(verdatData.getAsuransiTambahan(messageData));
        entity.setEng_capacity(verdatData.getEngCapacity(messageData));
        entity.setSkema_pembiayaan(verdatData.getSkemaPembiayaan(messageData));
        entity.setTotal_interest_amount(verdatData.getTotalInterestAmount(messageData));
        entity.setInsurance_credit_fee(verdatData.getInsuranceCreditFee(messageData));
        entity.setJatuh_tempo(verdatData.getJatuhTempo(messageData));
        entity.setObj_pembiayaan(verdatData.getObjPembiayaan(messageData));
        entity.setInternal_sales_head(verdatData.getInternalSalesHead(messageData));
        entity.setFin_scheme_code(verdatData.getFinSchemeCode(messageData));
        entity.setNo_obligor_id(verdatData.getNoObligorId(messageData));
        entity.setNo_po_cl(verdatData.getNoPoCl(messageData));
        entity.setInterest_amount(verdatData.getInterestAmount(messageData));
        entity.setBiaya_asuransi_tambahan(verdatData.getBiayaAsuransiTambahan(messageData));
        entity.setJob_internal_sales_forced(verdatData.getJobInternalSalesForced(messageData));
        entity.setNama_internal_sales_forced(verdatData.getNamaInternalSalesForced(messageData));
        entity.setKeterangan_po(verdatData.getKeteranganPo(messageData));
        entity.setNilai_pelunasan(verdatData.getNilaiPelunasan(messageData));
        entity.setAlasan_cancel_po_cl(verdatData.getAlasanCancelPoCl(messageData));
        entity.setNotes_cancel_po_cl(verdatData.getNotesCancelPoCl(messageData));
        entity.setNik_reject_cancel_marketing(verdatData.getNikRejectCancelMarketing(messageData));
        entity.setUser_reject_cancel_marketing(verdatData.getUserRejectCancelMarketing(messageData));
        entity.setPic_dealer(verdatData.getPicDealer(messageData));
        entity.setFlagging_reject_cancel_mkt(verdatData.getFlaggingRejectCancelMkt(messageData));
        entity.setDeskripsi_reject_cancel_mkt(verdatData.getDeskripsiRejectCancelMkt(messageData));
        entity.setAlasan_reject_cancel_mkt(verdatData.getAlasanRejectCancelMkt(messageData));
        entity.setReject_cancel_source_app(verdatData.getRejectCancelSourceApp(messageData));
        entity.setDeskripsi_source_aplikasi(verdatData.getDeskripsiSourceAplikasi(messageData));
        entity.setAlasan_koreksi_po(verdatData.getAlasanKoreksiPo(messageData));
        entity.setNik_koreksi_po(verdatData.getNikKoreksiPo(messageData));
        entity.setTanggal_koreksi_po(verdatData.getTanggalKoreksiPo(messageData));
        entity.setTotal_koreksi_po(verdatData.getTotalKoreksiPo(messageData));
        entity.setCara_bayar_angsuran(verdatData.getCaraBayarAngsuran(messageData));
        entity.setStatus_aplikasi(verdatData.getStatusAplikasi(messageData));
        entity.setJumlah_nasabah_ditolak(verdatData.getJumlahNasabahDitolak(messageData));
        entity.setJumlah_cetak_po_cl(verdatData.getJumlahCetakPoCl(messageData));
        entity.setJumlah_po_cl_belum_cetak(verdatData.getJumlahPoClBelumCetak(messageData));
        entity.setJumlah_cancel_po_cl(verdatData.getJumlahCancelPoCl(messageData));
        entity.setJumlah_koreksi_po_cl(verdatData.getJumlahKoreksiPoCl(messageData));
        entity.setJumlah_po_cl_pending(verdatData.getJumlahPoClPending(messageData));
        entity.setJumlah_nasabah_cancel_ppd(verdatData.getJumlahNasabahCancelPpd(messageData));
        entity.setJumlah_tagihan_belum_ppd(verdatData.getJumlahTagihanBelumPpd(messageData));
        entity.setJumlah_reject_cancel_marketing(verdatData.getJumlahRejectCancelMarketing(messageData));
        entity.setTipe_debitur(verdatData.getTipeDebitur(messageData));
        entity.setTanggal_entry(verdatData.getTanggalEntry(messageData));
        entity.setTanggal_approval(verdatData.getTanggalApproval(messageData));
        entity.setTanggal_cetak(verdatData.getTanggalCetak(messageData));
        entity.setTanggal_cancel(verdatData.getTanggalCancel(messageData));
        entity.setTanggal_koreksi(verdatData.getTanggalKoreksi(messageData));
    }

    private void saveEntity(DatalakeEntity entity) {
        String currentFormDesc = "VERDAT";
        datalakeRepository.save(entity);
        logger.info("Entity saved: Order ID = {}, Current Form = {}", entity.getOrder_id(), currentFormDesc);
    }

}
